/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Component;

import DAO.ChiTietQuyenDAO;
import DAO.NhanVienDAO;
import DAO.NhomQuyenDAO;
import DTO.ChiTietQuyenDTO;
import DTO.NhanVienDTO;
import DTO.NhomQuyenDTO;
import DTO.TaiKhoanDTO;

import GUI.Login;
import GUI.Main;
import GUI.Panel.NhanVien;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author anvan
 */
public class MenuTaskbar extends javax.swing.JPanel {
    NhanVien nhanVien;
    Main main;
    TaiKhoanDTO user;
    JLabel lblTenNhomQuyen, lblUsername;
    
    Color FontColor = new Color(96, 125, 139);
    Color DefaultColor = new Color(255, 255, 255);
    Color HowerFontColor = new Color(1, 87, 155);
    Color HowerBackgroundColor = new Color(187, 222, 251);
    
    private ArrayList<ChiTietQuyenDTO> listQuyen;
    NhomQuyenDTO nhomQuyenDTO;
    public NhanVienDTO nhanVienDTO;

    public MenuTaskbar() {
        initComponents();
        jScrollPane1 = new JScrollPane(jPnlCenter, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setBorder(new EmptyBorder(0, 0, 0, 0));
        this.add(jScrollPane1, BorderLayout.CENTER);
    }
    
    public MenuTaskbar(Main main) {
        this.main = main;
        initComponents();
    }
    
    public MenuTaskbar(Main main, TaiKhoanDTO tk) {
        this.main = main;
        this.user = tk;
        this.nhomQuyenDTO = NhomQuyenDAO.getInstance().selectById(Integer.toString(tk.getManhomquyen()));
        this.nhanVienDTO = NhanVienDAO.getInstance().selectById(Integer.toString(tk.getManv()));
        listQuyen = ChiTietQuyenDAO.getInstance().selectAll(Integer.toString(tk.getManhomquyen()));
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPnlTop = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPnlCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPnlMenu = new javax.swing.JPanel();
        jPnlHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jPnlSanPham = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblIcon4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblIcon6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblIcon2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblIcon1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblIcon3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblIcon5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblIcon7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblIcon8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblIcon9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIcon10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblIcon11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblIcon12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPnlBottom = new javax.swing.JPanel();
        jPnlDangXuat = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblIcon13 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(250, 1400));
        setLayout(new java.awt.BorderLayout());

        jPnlTop.setBackground(new java.awt.Color(255, 255, 255));
        jPnlTop.setPreferredSize(new java.awt.Dimension(250, 80));
        jPnlTop.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setPreferredSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPnlTop.add(jPanel16, java.awt.BorderLayout.SOUTH);

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setPreferredSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        jPnlTop.add(jPanel17, java.awt.BorderLayout.EAST);

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPnlTop.add(jPanel18, java.awt.BorderLayout.CENTER);

        add(jPnlTop, java.awt.BorderLayout.NORTH);

        jPnlCenter.setBackground(new java.awt.Color(255, 255, 255));
        jPnlCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPnlCenter.setPreferredSize(new java.awt.Dimension(250, 770));
        jPnlCenter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        jPnlCenter.add(jScrollPane1);

        jPnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPnlMenu.setPreferredSize(new java.awt.Dimension(250, 770));
        jPnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlHome.setBackground(new java.awt.Color(255, 255, 255));
        jPnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Trang chủ");
        jPnlHome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/home-button.png"))); // NOI18N
        lblIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        jPnlHome.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPnlMenu.add(jPnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        jPnlSanPham.setBackground(new java.awt.Color(255, 255, 255));
        jPnlSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlSanPhamMousePressed(evt);
            }
        });
        jPnlSanPham.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Sản phẩm");
        jPnlSanPham.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        lblIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/product.png"))); // NOI18N
        lblIcon4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPnlSanPham.add(lblIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPnlMenu.add(jPnlSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 50));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/tag.png"))); // NOI18N
        lblIcon6.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel9.add(lblIcon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Thuộc tính");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        jPnlMenu.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Khu vực kho");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/placeholder.png"))); // NOI18N
        lblIcon2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel4.add(lblIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPnlMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Phiếu nhập");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/import.png"))); // NOI18N
        lblIcon1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(lblIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPnlMenu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/export.png"))); // NOI18N
        lblIcon3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel5.add(lblIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Phiếu xuất");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        jPnlMenu.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/guest.png"))); // NOI18N
        lblIcon5.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel6.add(lblIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Khách hàng");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        jPnlMenu.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 250, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/supplier.png"))); // NOI18N
        lblIcon7.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel8.add(lblIcon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Nhà cung cấp");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        jPnlMenu.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 50));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Nhân viên");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        lblIcon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/staff.png"))); // NOI18N
        lblIcon8.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel10.add(lblIcon8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPnlMenu.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 250, 50));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/profile.png"))); // NOI18N
        lblIcon9.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel11.add(lblIcon9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Tài khoản");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        jPnlMenu.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 250, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/statistical.png"))); // NOI18N
        lblIcon10.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(lblIcon10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Thống kê");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        jPnlMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 250, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/decentralization.png"))); // NOI18N
        lblIcon11.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel12.add(lblIcon11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Phân quyền");
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        jPnlMenu.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 250, 50));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/decentralization.png"))); // NOI18N
        lblIcon12.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel13.add(lblIcon12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Test");
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        jPnlMenu.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 250, 50));

        jPnlCenter.add(jPnlMenu);

        add(jPnlCenter, java.awt.BorderLayout.CENTER);

        jPnlBottom.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBottom.setPreferredSize(new java.awt.Dimension(250, 50));
        jPnlBottom.setLayout(new java.awt.BorderLayout());

        jPnlDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        jPnlDangXuat.setPreferredSize(new java.awt.Dimension(250, 50));
        jPnlDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlDangXuatMousePressed(evt);
            }
        });
        jPnlDangXuat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Đăng xuất");
        jPnlDangXuat.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        lblIcon13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/log-out.png"))); // NOI18N
        lblIcon13.setPreferredSize(new java.awt.Dimension(50, 50));
        jPnlDangXuat.add(lblIcon13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPnlBottom.add(jPnlDangXuat, java.awt.BorderLayout.CENTER);

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setPreferredSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPnlBottom.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        add(jPnlBottom, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jPnlDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlDangXuatMousePressed
        int input = JOptionPane.showConfirmDialog(null,
                        "Bạn có chắc chắn muốn đăng xuất?", "Đăng xuất",
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (input == 0) {
                    Login login = new Login();
                    this.main.dispose();
                    login.setVisible(true);
                }
    }//GEN-LAST:event_jPnlDangXuatMousePressed

    private void jPnlSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlSanPhamMousePressed
        main.jPnlContent.removeAll();
        NhanVien p = new NhanVien();
        main.jPnlContent.add(p).setVisible(true);
    }//GEN-LAST:event_jPnlSanPhamMousePressed


    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPnlBottom;
    private javax.swing.JPanel jPnlCenter;
    private javax.swing.JPanel jPnlDangXuat;
    private javax.swing.JPanel jPnlHome;
    private javax.swing.JPanel jPnlMenu;
    private javax.swing.JPanel jPnlSanPham;
    private javax.swing.JPanel jPnlTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblIcon10;
    private javax.swing.JLabel lblIcon11;
    private javax.swing.JLabel lblIcon12;
    private javax.swing.JLabel lblIcon13;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblIcon3;
    private javax.swing.JLabel lblIcon4;
    private javax.swing.JLabel lblIcon5;
    private javax.swing.JLabel lblIcon6;
    private javax.swing.JLabel lblIcon7;
    private javax.swing.JLabel lblIcon8;
    private javax.swing.JLabel lblIcon9;
    // End of variables declaration//GEN-END:variables
}
